version: 2

formats: []

build:
  os: ubuntu-22.04
  tools:
    python: 3.11

sphinx:
  configuration: docs/readthedocs/conf.py

python:
  install:
    - requirements: docs/readthedocs/requirements.txt
